services:
  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD", "healthcheck.sh", "--connect"]
      timeout: 30s
    container_name: mariadb
    hostname: mariadb
    build:
      context: docker
    networks:
      - mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

networks:
  mariadb:
    name: mariadb
    external: false

volumes:
  mariadb:
